### ISSUE TITLE
模拟器上使用没问题，但是在真机上，图片就不显示了

### ISSUE THREAD

**Issue by DoctorWei** [gy134340/wxml2canvas#1]
demo直接跑的，模拟器上使用没问题，但是在真机上，图片就不显示了

**Comment by gy134340** [comment]
现在不在写小程序了，不过这个库的源码很简单，应该不是很难 debug, 是一些最基础的功能。

1. 可以尝试在其中加一些 debugger 调试下，看看是最近一些 api 变动，还是当初有些情景没有考虑到
2. 如果觉得代码还是比较长，可以尝试一个一个注释掉一些无关的函数
